# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Modular PC Open Source
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Community Projects for modular and upgradable Mini and All-In-One PC & Workstation
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://v-squared.github.io/" # the base hostname & protocol for your site
twitter_username: villagevidock
github_username:  v-squared
include: ["_pages","_javascript"]
exclude: ["node_modules"]

# Build settings
markdown: kramdown
