// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/ae78852d870ca773041d91f72b25426c95c84805/ngstorage/ngstorage.d.ts
declare namespace angular.storage {

    export interface IStorageService {
        $default(items: {}): IStorageService;
        $reset(items?: {}): IStorageService;
        $apply(): void;
        $sync(): void;
        [key: string]: any;
    }

    export interface IStorageProvider extends angular.IServiceProvider {

        get<T>(key:string): T;
        set<T>(key:string, value:T): T;

        setKeyPrefix(prefix: string): void;
        setSerializer(serializer: (value: any)=>string): void;
        setDeserializer(deserializer: (value: string)=>any): void;
    }
}
